# -*- coding: utf-8 -*-
"""Text_to_Image_generation_using_DALL-E_Mini(Project_2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12h8nrPfaqzQCldzTcUIiJtj-YVWk_feJ

# Install Required Libraries
"""

!pip install min-dalle -q

from min_dalle import MinDalle
model = MinDalle(is_mega=True, is_reusable=True)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# text = "A mobilephone"
# seed = 6
# grid_size = 2
# display(model.generate_image(text, seed, grid_size))

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# text = "lion"
# seed = 6
# grid_size = 2
# display(model.generate_image(text, seed, grid_size))

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# text = "Sunflower garden"
# seed = 6
# grid_size = 2
# display(model.generate_image(text, seed, grid_size))

